# Generated by Django 6.0.5 on 2026-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_rename_order_date_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=500),
        ),
    ]
